using UdonSharp;
using UdonSharp.CE.Async;
using UnityEngine;
using UnityEngine.UI;

namespace UdonSharp.CE.Samples.Async
{
    /// <summary>
    /// Example cutscene controller demonstrating CE.Async usage.
    ///
    /// NOTE: Full async transformation is in development.
    /// This example shows the intended API and expected behavior.
    ///
    /// When async transformation is complete, methods returning UdonTask
    /// will be automatically transformed into state machines.
    /// </summary>
    /// <remarks>
    /// The CE.Async system transforms async methods into state machines that use
    /// SendCustomEventDelayedSeconds/Frames for continuation.
    ///
    /// Expected transformation for PlayIntro():
    /// - Generated fields: __async_PlayIntro_state, __async_PlayIntro_result
    /// - Generated method: __async_PlayIntro_MoveNext()
    /// - Entry point initializes state and calls MoveNext
    /// - Each await becomes a state transition with delayed event
    /// </remarks>
    public class CutsceneExample : UdonSharpBehaviour
    {
        #region Serialized Fields

        [Header("UI")]
        [SerializeField] private CanvasGroup fadeCanvasGroup;
        [SerializeField] private Text titleText;

        [Header("Audio")]
        [SerializeField] private AudioSource musicSource;

        [Header("Animation")]
        [SerializeField] private Animator cameraAnimator;

        [Header("Settings")]
        [SerializeField] private float fadeDuration = 1f;
        [SerializeField] private float titleDisplayTime = 3f;

        #endregion

        #region Private State

        private CancellationTokenSource _cutsceneCts;

        // Manual state machine fields (generated by compiler in final version)
        private int _playIntroState;
        private float _fadeStartTime;
        private float _fadeStartAlpha;
        private float _fadeTargetAlpha;

        #endregion

        #region Public API

        /// <summary>
        /// Starts the intro cutscene.
        /// </summary>
        public void StartIntro()
        {
            _cutsceneCts = new CancellationTokenSource();
            PlayIntro();
        }

        /// <summary>
        /// Cancels the currently playing cutscene.
        /// </summary>
        public void CancelCutscene()
        {
            if (_cutsceneCts != null)
            {
                _cutsceneCts.Cancel();
                Debug.Log("[Cutscene] Canceled by user");
            }
        }

        #endregion

        #region Async Methods (Expected API)

        /// <summary>
        /// Plays the intro cutscene sequence.
        ///
        /// When async transformation is complete, this method signature:
        ///   public UdonTask PlayIntro()
        /// Will be automatically transformed to use state machine pattern.
        ///
        /// For now, this is implemented manually to demonstrate the pattern.
        /// </summary>
        public UdonTask PlayIntro()
        {
            // Initialize state machine
            _playIntroState = 0;
            _PlayIntro_MoveNext();

            return new UdonTask { _status = TaskStatus.Running };
        }

        /// <summary>
        /// Manual state machine implementation.
        /// The compiler will generate this automatically in the future.
        /// </summary>
        public void _PlayIntro_MoveNext()
        {
            // Check for cancellation at each state
            if (_cutsceneCts != null && _cutsceneCts.IsCancellationRequested)
            {
                Debug.Log("[Cutscene] Execution canceled");
                return;
            }

            switch (_playIntroState)
            {
                case 0:
                    // State 0: Start fade to black
                    Debug.Log("[Cutscene] Starting intro...");
                    StartFade(1f); // Fade to black
                    _playIntroState = 1;
                    SendCustomEventDelayedSeconds(nameof(_PlayIntro_MoveNext), fadeDuration);
                    return;

                case 1:
                    // State 1: Show title
                    Debug.Log("[Cutscene] Showing title...");
                    ShowTitle("Welcome to the World");
                    _playIntroState = 2;
                    SendCustomEventDelayedSeconds(nameof(_PlayIntro_MoveNext), titleDisplayTime);
                    return;

                case 2:
                    // State 2: Hide title and start music
                    Debug.Log("[Cutscene] Starting music...");
                    HideTitle();
                    PlayMusic();
                    _playIntroState = 3;
                    SendCustomEventDelayedFrames(nameof(_PlayIntro_MoveNext), 1);
                    return;

                case 3:
                    // State 3: Play camera animation
                    Debug.Log("[Cutscene] Playing camera animation...");
                    PlayCameraAnimation("IntroCamera");
                    _playIntroState = 4;
                    SendCustomEventDelayedSeconds(nameof(_PlayIntro_MoveNext), 5f); // Animation duration
                    return;

                case 4:
                    // State 4: Fade from black
                    Debug.Log("[Cutscene] Fading in...");
                    StartFade(0f); // Fade to clear
                    _playIntroState = 5;
                    SendCustomEventDelayedSeconds(nameof(_PlayIntro_MoveNext), fadeDuration);
                    return;

                case 5:
                    // State 5: Complete
                    Debug.Log("[Cutscene] Intro complete!");
                    return;
            }
        }

        #endregion

        #region Helper Methods

        /// <summary>
        /// Starts a fade animation on the canvas group.
        /// </summary>
        private void StartFade(float targetAlpha)
        {
            if (fadeCanvasGroup == null) return;

            _fadeStartTime = Time.time;
            _fadeStartAlpha = fadeCanvasGroup.alpha;
            _fadeTargetAlpha = targetAlpha;

            // Start fade update loop
            SendCustomEventDelayedFrames(nameof(_UpdateFade), 1);
        }

        /// <summary>
        /// Updates the fade animation each frame.
        /// </summary>
        public void _UpdateFade()
        {
            if (fadeCanvasGroup == null) return;

            float elapsed = Time.time - _fadeStartTime;
            float t = Mathf.Clamp01(elapsed / fadeDuration);

            fadeCanvasGroup.alpha = Mathf.Lerp(_fadeStartAlpha, _fadeTargetAlpha, t);

            if (t < 1f)
            {
                SendCustomEventDelayedFrames(nameof(_UpdateFade), 1);
            }
        }

        /// <summary>
        /// Shows the title text.
        /// </summary>
        private void ShowTitle(string text)
        {
            if (titleText != null)
            {
                titleText.text = text;
                titleText.gameObject.SetActive(true);
            }
        }

        /// <summary>
        /// Hides the title text.
        /// </summary>
        private void HideTitle()
        {
            if (titleText != null)
            {
                titleText.gameObject.SetActive(false);
            }
        }

        /// <summary>
        /// Starts playing background music.
        /// </summary>
        private void PlayMusic()
        {
            if (musicSource != null && !musicSource.isPlaying)
            {
                musicSource.Play();
            }
        }

        /// <summary>
        /// Plays a camera animation.
        /// </summary>
        private void PlayCameraAnimation(string animationName)
        {
            if (cameraAnimator != null)
            {
                cameraAnimator.Play(animationName);
            }
        }

        #endregion
    }
}
